### ISSUE TITLE
Flaky test: VS Code 'file on disk changes'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#478]
macOS x86_64
https://github.com/quick-lint/quick-lint-js/runs/4052952235?check_suite_focus=true

```
Running file on disk changes ...

AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   {
-     code: 'E034',
-     endCharacter: 5,
-     endLine: 1,
-     message: 'redeclaration of variable: x',
-     severity: 0,
-     source: 'quick-lint-js',
-     startCharacter: 4,
-     startLine: 1
-   }
- ]
	at /Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/vscode-tests.js:170:14
	at pollAsync (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/vscode-tests.js:1252:9)
	at runNextTicks (internal/process/task_queues.js:59:5)
	at processTimers (internal/timers.js:472:9)
	at async file on disk changes (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/vscode-tests.js:168:5)
	at async runTestAsync (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/test-support.js:51:5)
	at async runTestsAsync (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/test-support.js:35:7)
	at async testMainAsync (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/test-support.js:22:5)
	at async Object.runAsync [as run] (/Users/runner/work/quick-lint-js/quick-lint-js/plugin/vscode/test/vscode-tests.js:1277:3)

FAIL    file on disk changes

Error: test failed

Exit code:   1
Done
```

**Comment by strager** [comment]
It failed on Windows x86 too: https://github.com/quick-lint/quick-lint-js/runs/4088084137?check_suite_focus=true
```
Running file on disk changes ...

AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   {
-     code: 'E034',
-     endCharacter: 5,
-     endLine: 1,
-     message: 'redeclaration of variable: x',
-     severity: 0,
-     source: 'quick-lint-js',
-     startCharacter: 4,
-     startLine: 1
-   }
- ]
	at d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\vscode-tests.js:170:14
	at pollAsync (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\vscode-tests.js:1252:9)
	at async file on disk changes (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\vscode-tests.js:168:5)
	at async runTestAsync (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\test-support.js:51:5)
	at async runTestsAsync (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\test-support.js:35:7)
	at async testMainAsync (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\test-support.js:22:5)
	at async Object.runAsync [as run] (d:\a\quick-lint-js\quick-lint-js\plugin\vscode\test\vscode-tests.js:1277:3)

FAIL    file on disk changes

Error: test failed

Error: test failed

Exit code:   1
Done
```

**Comment by strager** [comment]
I haven't been able to reproduce this issue locally on my Windows machine. =\

**Comment by strager** [comment]
I reproduced it on my Mac machine. I think it has to do with performance. (Slower machine = more flaky.)

**Comment by strager** [comment]
Flakiness worked around in commit 66abe7269984bf8913f885be5eac6b6f414f5b37.
